version: '3.8'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    
  app:
    container_name: app
    build: 
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/app
    ports:
      - "8000:8000"
    working_dir: /var/www/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    